//------------------------------------------------------------------------------
// <auto-generated>
<<<<<<< HEAD
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6421
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
=======
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.8000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
>>>>>>> f3f47d0cc5bfbfd5371eeae9b4216f12b18821d5
// </auto-generated>
//------------------------------------------------------------------------------

// 
<<<<<<< HEAD
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.6421.
=======
// Este código de origem foi gerado automaticamente por Microsoft.VSDesigner, versão 2.0.50727.8000.
>>>>>>> f3f47d0cc5bfbfd5371eeae9b4216f12b18821d5
// 
#pragma warning disable 1591

namespace WindowsFormsApplication1.localhost {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
<<<<<<< HEAD
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
=======
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
>>>>>>> f3f47d0cc5bfbfd5371eeae9b4216f12b18821d5
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://127.0.0.1/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback insereOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::WindowsFormsApplication1.Properties.Settings.Default.WindowsFormsApplication1_localhost_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event insereCompletedEventHandler insereCompleted;
        
        /// <remarks/>
        public event consultaCompletedEventHandler consultaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://127.0.0.1/insere", RequestNamespace="http://127.0.0.1/", ResponseNamespace="http://127.0.0.1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
<<<<<<< HEAD
        public void insere(int Matricula, int pes, int equipamento, string Data, short Sentido, short status_sentido, short area_de, short area_para) {
            this.Invoke("insere", new object[] {
                        Matricula,
                        pes,
                        equipamento,
                        Data,
                        Sentido,
                        status_sentido,
                        area_de,
                        area_para});
        }
        
        /// <remarks/>
        public void insereAsync(int Matricula, int pes, int equipamento, string Data, short Sentido, short status_sentido, short area_de, short area_para) {
            this.insereAsync(Matricula, pes, equipamento, Data, Sentido, status_sentido, area_de, area_para, null);
        }
        
        /// <remarks/>
        public void insereAsync(int Matricula, int pes, int equipamento, string Data, short Sentido, short status_sentido, short area_de, short area_para, object userState) {
=======
        public void insere(int Matricula, string Data, int Sentido) {
            this.Invoke("insere", new object[] {
                        Matricula,
                        Data,
                        Sentido});
        }
        
        /// <remarks/>
        public void insereAsync(int Matricula, string Data, int Sentido) {
            this.insereAsync(Matricula, Data, Sentido, null);
        }
        
        /// <remarks/>
        public void insereAsync(int Matricula, string Data, int Sentido, object userState) {
>>>>>>> f3f47d0cc5bfbfd5371eeae9b4216f12b18821d5
            if ((this.insereOperationCompleted == null)) {
                this.insereOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsereOperationCompleted);
            }
            this.InvokeAsync("insere", new object[] {
                        Matricula,
<<<<<<< HEAD
                        pes,
                        equipamento,
                        Data,
                        Sentido,
                        status_sentido,
                        area_de,
                        area_para}, this.insereOperationCompleted, userState);
=======
                        Data,
                        Sentido}, this.insereOperationCompleted, userState);
>>>>>>> f3f47d0cc5bfbfd5371eeae9b4216f12b18821d5
        }
        
        private void OninsereOperationCompleted(object arg) {
            if ((this.insereCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insereCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://127.0.0.1/consulta", RequestNamespace="http://127.0.0.1/", ResponseNamespace="http://127.0.0.1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string consulta(string matricula) {
            object[] results = this.Invoke("consulta", new object[] {
                        matricula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaAsync(string matricula) {
            this.consultaAsync(matricula, null);
        }
        
        /// <remarks/>
        public void consultaAsync(string matricula, object userState) {
            if ((this.consultaOperationCompleted == null)) {
                this.consultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaOperationCompleted);
            }
            this.InvokeAsync("consulta", new object[] {
                        matricula}, this.consultaOperationCompleted, userState);
        }
        
        private void OnconsultaOperationCompleted(object arg) {
            if ((this.consultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaCompleted(this, new consultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
<<<<<<< HEAD
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void insereCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void consultaCompletedEventHandler(object sender, consultaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
=======
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void insereCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void consultaCompletedEventHandler(object sender, consultaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
>>>>>>> f3f47d0cc5bfbfd5371eeae9b4216f12b18821d5
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591