//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.8000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8000.
// 
namespace SmartDeviceProject1.localhost {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://127.0.0.1/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service() {
            this.Url = "http://localhost:3374/WebSite1/Service.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://127.0.0.1/insere", RequestNamespace="http://127.0.0.1/", ResponseNamespace="http://127.0.0.1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void insere(int Matricula, string Data, int Sentido) {
            this.Invoke("insere", new object[] {
                        Matricula,
                        Data,
                        Sentido});
        }
        
        /// <remarks/>
        public System.IAsyncResult Begininsere(int Matricula, string Data, int Sentido, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("insere", new object[] {
                        Matricula,
                        Data,
                        Sentido}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endinsere(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://127.0.0.1/consulta", RequestNamespace="http://127.0.0.1/", ResponseNamespace="http://127.0.0.1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string consulta(string matricula) {
            object[] results = this.Invoke("consulta", new object[] {
                        matricula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginconsulta(string matricula, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("consulta", new object[] {
                        matricula}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endconsulta(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
